import { describe, expect } from 'vitest'
import { effect } from './support/effect-test.js'
import { Effect } from 'effect'
import * as publicApi from '../src/index.js'
import type { StorageService } from '../src/index.js'

const expectedRuntimeExports = [
  'FIRST_VERSION',
  'SaveEnvelopeSchema',
  'saveEnvelope',
  'isFromFuture',
  'DEFAULT_MAX_SAVE_BYTES',
  'sealSaveEnvelope',
  'validateSaveEnvelope',
  'fixedUint8Array',
  'saveDurably',
  'loadDurably',
  'StorageError',
  'SaveDecodeError',
  'SaveEnvelopeDraftSchema',
  'DuplicateFormatError',
  'defineFormat',
  'encodeSave',
  'decodeSave',
  'decodeMinecraftJavaSave',
  'decodeMinecraftJson',
  'SAVE_STORE_NAME',
  'INSERTION_INDEX_NAME',
  'STORE_LAYOUT_VERSION',
  'QUOTA_EXCEEDED_MARKER',
  'isQuotaExceeded',
  'makeIndexedDbStorage',
  'indexedDbStorageLayer',
  'saveTo',
  'saveBatchEntry',
  'saveBatch',
  'loadFrom',
  'listFrom',
  'emptyRegistry',
  'registerFormat',
  'registerFormats',
  'lookupFormat',
  'describeRegistry',
  'SaveKey',
  'StoragePort',
  'makeInMemoryStorage',
  'InMemoryStorageLayer',
  'failingStorageLayer',
  'withStorageRetry',
  'saveKeyForWorld',
  'ANVIL_SECTOR_BYTES',
  'ANVIL_HEADER_SECTORS',
  'ANVIL_HEADER_BYTES',
  'ANVIL_REGION_CHUNK_SIDE',
  'ANVIL_CHUNK_COUNT',
  'ANVIL_MAX_CHUNK_SECTORS',
  'ANVIL_MAX_REGION_BYTES',
  'ANVIL_EXTERNAL_STREAM_FLAG',
  'ANVIL_EXTERNAL_CHUNK_THRESHOLD',
  'ANVIL_EXTERNAL_FILE_EXTENSION',
  'ANVIL_COMPRESSION_IDS',
  'AnvilRegionError',
  'anvilCompressionFromId',
  'anvilCompressionId',
  'anvilRegion',
  'decodeAnvilRegion',
  'encodeAnvilRegion',
  'MINECRAFT_COMPRESSION',
  'MINECRAFT_COMPRESSION_MAX_BYTES',
  'MinecraftCompressionError',
  'MINECRAFT_JAVA_SAVE_DEFAULT_MAX_FILES',
  'MINECRAFT_JAVA_SAVE_DEFAULT_MAX_FILE_BYTES',
  'MINECRAFT_JAVA_SAVE_DEFAULT_MAX_TOTAL_BYTES',
  'MinecraftJavaSaveError',
  'MinecraftJsonError',
  'compressMinecraft',
  'decompressMinecraft',
  'MinecraftLz4Error',
  'encodeLz4BlockStream',
  'decodeLz4BlockStream',
  'encodeCompressedNbt',
  'decodeCompressedNbt',
  'MINECRAFT_NBT_FILE_COMPRESSION',
  'MINECRAFT_SESSION_LOCK_BYTES',
  'encodeMinecraftNbtFile',
  'decodeMinecraftNbtFile',
  'encodeMinecraftSessionLock',
  'decodeMinecraftSessionLock',
  'errorReason',
  'NBT_TAG_IDS',
  'NbtFormatError',
  'DEFAULT_NBT_CODEC_OPTIONS',
  'encodeModifiedUtf8',
  'decodeModifiedUtf8',
  'encodeNbt',
  'decodeNbt',
  'nbtEnd',
  'nbtByte',
  'nbtShort',
  'nbtInt',
  'nbtLong',
  'nbtFloat',
  'nbtDouble',
  'nbtByteArray',
  'nbtString',
  'nbtList',
  'nbtCompound',
  'nbtIntArray',
  'nbtLongArray',
  'nbtDocument',
  'isMinecraftNbtDocument',
  'ANVIL_REGION_BLOCK_SIDE',
  'minecraftDimensionDirectory',
  'anvilRegionCoordinate',
  'anvilChunkLocalCoordinate',
  'anvilChunkIndex',
  'anvilRegionFileName',
  'minecraftRegionFilePath',
  'minecraftExternalChunkFileName',
  'minecraftExternalChunkFilePath',
  'minecraftLevelDataPath',
  'minecraftLevelDataBackupPath',
  'minecraftIconPath',
  'minecraftSessionLockPath',
  'minecraftPlayerDataPath',
  'minecraftStatsPath',
  'minecraftAdvancementsPath',
  'minecraftDataFilePath',
  'minecraftRaidsPath',
  'minecraftScoreboardPath',
  'minecraftWorldBorderPath',
  'minecraftEnderDragonFightPath',
  'minecraftWanderingTraderPath',
  'minecraftCustomBossEventsPath',
  'minecraftWeatherPath',
  'minecraftScheduledEventsPath',
  'minecraftGameRulesPath',
  'minecraftWorldGenSettingsPath',
  'minecraftWorldClocksPath',
  'minecraftWorldClockPath',
  'minecraftMapFilePath',
  'minecraftLastIdPath',
  'minecraftChunkTicketsPath',
  'minecraftCommandStoragePath',
  'minecraftWorldResourcePackPath',
  'minecraftStructurePath',
  'MINECRAFT_EXTERNAL_CHUNK_DEFAULT_MAX_BYTES',
  'MinecraftRegionFilesError',
  'encodeMinecraftExternalChunkFile',
  'decodeMinecraftExternalChunkFile',
  'encodeMinecraftJavaSave',
  'encodeMinecraftJson',
  'encodeMinecraftRegionFiles',
  'decodeMinecraftRegionFiles',
  'isMinecraftJsonValue',
  'minecraftJavaSaveError',
  'parseMinecraftJavaSavePath',
  'resolveMinecraftJavaSaveOptions',
  'throwMinecraftJavaSaveError',
  'validateMinecraftJavaSave',
  'validateMinecraftJavaSaveFiles',
] as const

describe('public API', () => {
  effect('re-exports the domain runtime values from the barrel', () =>
    Effect.sync(() => {
      expect(Object.keys(publicApi).sort()).toEqual([...expectedRuntimeExports].sort())
    }),
  )

  effect('keeps the complete StorageService boundary available', () =>
    Effect.gen(function* () {
      const service = yield* publicApi.makeInMemoryStorage
      const typedService: StorageService = service

      expect(typeof typedService.get).toBe('function')
      expect(typeof typedService.put).toBe('function')
      expect(typeof typedService.remove).toBe('function')
      expect(typeof typedService.commitBatch).toBe('function')
      expect(typeof typedService.readBatch).toBe('function')
      expect(typedService).toHaveProperty('keys')
    }),
  )
})
